Repository podkrepi-bg/api, pull requests merged in 2022-03, with the labels that each got.

#116 Added delete many beneficiaries
  apps/api/src/beneficiary/beneficiary.controller.ts
  apps/api/src/beneficiary/beneficiary.service.ts
  apps/api/src/beneficiary/dto/delete-many-beneficiary.dto.ts
  db/seed/vault.seed.ts
Labels: bootcamp

#124 [Withdrawal] CRUD functionalities
  apps/api/src/app/app.module.ts
  apps/api/src/withdrawal/dto/create-withdrawal.dto.ts
  apps/api/src/withdrawal/dto/update-withdrawal.dto.ts
  apps/api/src/withdrawal/entities/withdrawal.entity.ts
  apps/api/src/withdrawal/withdrawal.controller.spec.ts
  apps/api/src/withdrawal/withdrawal.controller.ts
  apps/api/src/withdrawal/withdrawal.module.ts
  apps/api/src/withdrawal/withdrawal.service.spec.ts
  apps/api/src/withdrawal/withdrawal.service.ts
Labels: enhancement

#133 Fixed campaign types list endpoint to be public
  apps/api/src/campaign-types/campaign-types.controller.ts
Labels: bootcamp

#137 Fixed create campaign type dto
  apps/api/src/campaign-types/dto/create-campaign-type.dto.ts
Labels: bug, bootcamp

#135 Implement get all user donations
  apps/api/src/account/account.controller.ts
  apps/api/src/donations/donations.controller.ts
  apps/api/src/donations/donations.service.ts
Labels: bootcamp

#139 Added expose to fields in create campaign type dto
  apps/api/src/campaign-types/dto/create-campaign-type.dto.ts
Labels: bug, bootcamp

#143 Adding fields (file type and role) to campaign file entity.
  .devcontainer/devcontainer.json
  .github/workflows/codeql-analysis.yml
  .vscode/extensions.json
  apps/api/src/app/app.service.spec.ts
  apps/api/src/app/app.service.ts
  apps/api/src/campaign-file/campaign-file.controller.ts
  apps/api/src/campaign-file/campaign-file.service.ts
  apps/api/src/campaign-file/dto/create-campaign-file.dto.ts
  apps/api/src/domain/generated/campaignFile/dto/create-campaignFile.dto.ts
  apps/api/src/domain/generated/campaignFile/dto/update-campaignFile.dto.ts
  apps/api/src/domain/generated/campaignFile/entities/campaignFile.entity.ts
  apps/api/src/donations/dto/create-payment.dto.ts
  apps/api/src/health/health.controller.spec.ts
  apps/api/src/health/health.module.ts
  apps/api/src/prisma/prisma.health.ts
  apps/api/tsconfig.json
  migrations/20220320203725_campaign_role/migration.sql
  nest-cli.json
  podkrepi.dbml
  schema.prisma
  yarn.lock
Labels: bootcamp

#160 [CampaignType] Add category column for campaign type entity
  apps/api/src/campaign-types/dto/create-campaign-type.dto.ts
  apps/api/src/campaign/campaign.service.ts
  apps/api/src/domain/generated/campaignType/entities/campaignType.entity.ts
  db/seed/campaign-type.seed.ts
  db/seed/campaign.seed.ts
  migrations/20220324125236_campaign_type_category/migration.sql
  podkrepi.dbml
  schema.prisma
Labels: enhancement

#158 Added extra roles to enum CampaignFileRole
  apps/api/src/benefactor/dto/update-benefactor.dto.ts
  apps/api/src/campaign-file/campaign-file.controller.ts
  apps/api/src/campaign-file/campaign-file.service.ts
  apps/api/src/campaign/campaign.service.ts
  apps/api/src/donations/dto/create-payment.dto.ts
  migrations/20220323125223_added_extra_roles/migration.sql
  podkrepi.dbml
  schema.prisma
Labels: bootcamp
