Repository podkrepi-bg/api, pull requests merged in 2022-04, with the labels that each got.

#175 [Testing] Created unit tests for City entity
  apps/api/src/city/city.controller.spec.ts
  apps/api/src/city/city.controller.ts
  apps/api/src/city/city.service.ts
  apps/api/src/city/dto/create-city.dto.ts
Labels: test

#177 Coordinator tests
  apps/api/src/coordinator/coordinator.controller.spec.ts
  apps/api/src/coordinator/coordinator.service.spec.ts
Labels: bootcamp

#165 [expense] Created missing functionality for edit + more
  apps/api/src/expenses/expenses.controller.ts
  apps/api/src/expenses/expenses.service.ts
Labels: enhancement, bootcamp

#194 Country unit tests
  apps/api/src/country/country.controller.spec.ts
  apps/api/src/country/country.controller.ts
  apps/api/src/country/dto/create-country.dto.ts
Labels: bootcamp, unit testing

#187 [Testing] Refactored unit tests for Withdrawal entity
  apps/api/src/withdrawal/withdrawal.controller.spec.ts
  apps/api/src/withdrawal/withdrawal.service.ts
Labels: test
