Repository podkrepi-bg/api, pull requests merged in 2022-02, with the labels that each got.

#76 crud for Country entity (api)
  apps/api/src/app/app.module.ts
  apps/api/src/country/country.controller.spec.ts
  apps/api/src/country/country.controller.ts
  apps/api/src/country/country.module.ts
  apps/api/src/country/country.service.spec.ts
  apps/api/src/country/country.service.ts
  apps/api/src/country/dto/create-country.dto.ts
  apps/api/src/country/dto/update-country.dto.ts
  apps/api/src/country/entities/country.entity.ts
Labels: enhancement, bootcamp

#78 [Bootcamp] Coordinator model
  apps/api/src/app/app.module.ts
  apps/api/src/coordinator/coordinator.controller.spec.ts
  apps/api/src/coordinator/coordinator.controller.ts
  apps/api/src/coordinator/coordinator.module.ts
  apps/api/src/coordinator/coordinator.service.spec.ts
  apps/api/src/coordinator/coordinator.service.ts
  apps/api/src/coordinator/dto/create-coordinator.dto.ts
  apps/api/src/coordinator/entities/coordinator.entity.ts
  apps/api/src/domain/generated/coordinator/dto/connect-coordinator.dto.ts
  migrations/20220213130743_/migration.sql
  podkrepi.dbml
  schema.prisma
Labels: enhancement

#110 Vault entity crud
  apps/api/src/app/app.module.ts
  apps/api/src/campaign/campaign.service.ts
  apps/api/src/campaign/dto/create-campaign.dto.ts
  apps/api/src/domain/generated/vault/dto/create-vault.dto.ts
  apps/api/src/domain/generated/vault/dto/update-vault.dto.ts
  apps/api/src/domain/generated/vault/entities/vault.entity.ts
  apps/api/src/vault/dto/create-vault.dto.ts
  apps/api/src/vault/dto/update-vault.dto.ts
  apps/api/src/vault/entities/vault.entity.ts
  apps/api/src/vault/vault.controller.spec.ts
  apps/api/src/vault/vault.controller.ts
  apps/api/src/vault/vault.module.ts
  apps/api/src/vault/vault.service.spec.ts
  apps/api/src/vault/vault.service.ts
  migrations/20220223105052_added_name_to_vault_model/migration.sql
  podkrepi.dbml
  schema.prisma
Labels: enhancement, bootcamp

#104 [City entity] PostalCode and service fix
  apps/api/src/city/city.controller.spec.ts
  apps/api/src/city/city.service.ts
  apps/api/src/city/dto/create-city.dto.ts
  apps/api/src/domain/generated/beneficiary/dto/create-beneficiary.dto.ts
  apps/api/src/domain/generated/beneficiary/dto/update-beneficiary.dto.ts
  apps/api/src/domain/generated/beneficiary/entities/beneficiary.entity.ts
  apps/api/src/domain/generated/campaign/entities/campaign.entity.ts
  apps/api/src/domain/generated/city/dto/connect-city.dto.ts
  apps/api/src/domain/generated/city/dto/create-city.dto.ts
  apps/api/src/domain/generated/city/dto/update-city.dto.ts
  apps/api/src/domain/generated/city/entities/city.entity.ts
  apps/api/src/domain/generated/donation/entities/donation.entity.ts
  apps/api/src/domain/generated/person/dto/create-person.dto.ts
  apps/api/src/domain/generated/person/dto/update-person.dto.ts
  apps/api/src/domain/generated/person/entities/person.entity.ts
  apps/api/src/domain/generated/recurringDonation/entities/recurringDonation.entity.ts
  apps/api/src/domain/generated/transfer/entities/transfer.entity.ts
  apps/api/src/domain/generated/vault/entities/vault.entity.ts
  apps/api/src/domain/generated/withdrawal/entities/withdrawal.entity.ts
  podkrepi.dbml
  schema.prisma
Labels: bootcamp
